services:
    Pimcore\Bundle\CoreBundle\Command\OptimizeImageThumbnailsCommand:
        arguments:
            - '@Pimcore\Image\Optimizer'
        tags:
            - { name: console.command, command: 'pimcore:thumbnails:optimize-images' }

    Pimcore\Bundle\CoreBundle\Command\UpdateDataObjectSchemaCommand:
        arguments:
            - '@Pimcore\ClassDefinition\SchemaBuilderInterface'
        tags:
            - { name: console.command, command: 'pimcore:data-object:schema:update' }
